#!/bin/bash

# Read base configuration
[ -r /etc/default/bs-volumes ] && . /etc/default/bs-volumes

<% if @data.ephemeral[:raid] -%>
get_ephemeral_raid_dev() {
  MD_PATH=/dev/md
  if [ ! -d $MD_PATH ]; then return 1; fi

  eph_dev_name=`find $MD_PATH -name "*<%=@data.ephemeral.raid.name%>"`
  if [ "$eph_dev_name" == "" ]; then
    return 1;
  fi

  ephemeraid_dev=`readlink -f "$eph_dev_name" 2> /dev/null`

  echo $ephemeraid_dev
  return 0
}

ephemeraid_is_mounted() {
  ephraiddev=`get_ephemeral_raid_dev`
  if [ $? -eq 0 ]; then
    device_is_mounted $ephraiddev
    return $?
  fi
  # Named device doesn't exist, maybe we just mounted it
  ephraiddev=`grep ephemeraid /etc/mdadm/mdadm.conf`
  Return1Fail

  ephraiddev=`echo $ephraiddev | cut -d ' ' -f 2`
  df | grep "$ephraiddev" | grep mnt &> /dev/null
}

try_mount_raid() {
  if ! ephemeraid_is_mounted; then
    ephraid=`get_ephemeral_raid_dev`
    if [ $? -eq 0 ]; then
      # Try to mount it if device exists
      mount -t <%=@data.ephemeral.raid.format%> -o noatime \
        $ephraid <%=get_mount('raid', :ephemeral)%> >/dev/null 2>&1
      Return0Success
    fi
  else
    # device is mounted, all set
    return 0
  fi
  # fail otherwise
  return 1
}
<% end %>

<% if @data.ephemeral[:raid] %>
# Set up a RAID of all ephemeral devices
<% else %>
# Mount every ephemeral device to its specified destination
<% end %>
setup_ephemeral() {
  METADATA_URL="http://169.254.169.254/latest"
  ephemerals=$(curl --silent $METADATA_URL/meta-data/block-device-mapping/ | grep ephemeral)

  root_drive=`df -h | grep -v grep | awk 'NR==2{print $1}'`

  if [[ "$root_drive" == *"xvd"* ]]; then
    echo "Detected 'xvd' drive naming scheme (root: $root_drive)"
    DRIVE_SCHEME='xvd'
  else
    echo "Detected 'sd' drive naming scheme (root: $root_drive)"
    DRIVE_SCHEME='sd'
  fi

  drives=""
  ephemeral_count=0

  for e in $ephemerals; do
    device_name=$(curl --silent $METADATA_URL/meta-data/block-device-mapping/$e)
    device_name=$(echo $device_name | sed "s/sd/$DRIVE_SCHEME/")
    device_path="/dev/$device_name"
    if [ -b $device_path ]; then
      log_progress_msg "Detected ephemeral disk: $device_path"
      drives="$drives $device_path"
      ephemeral_count=$((ephemeral_count + 1 ))
    else
      log_progress_msg "Ephemeral disk $e, $device_path is not present. skipping"
    fi
  done

<% unless @data.ephemeral[:raid] %>
# Mount each ephemeral drive.
  <% @data[:ephemeral] && @data.ephemeral.each do |d,info| -%>
  # Formatting <%=d%> as <%=%>
  # Mounting to <%=info.format%>
  edevice= echo "<%=d%>" | sed "s/sd/$DRIVE_SCHEME/"
  req_fmt=<%info.format%>
  mnt_pnt=<%=get_mount(d, :ephemeral)%>
  [ ! -e $mnt_pnt ] && mkdir $mnt_pnt
  # Ensure drive exists
  echo $drives | grep $edevice > /dev/null 2>&1  &&
  fmt_as $req_fmt $edevice                       &&
  mount -t $req_fmt -o noatime $edevice $mnt_pnt && 
  log_success_msg "Formatted/mounted $edevice"   ||
  log_warning_msg "Failed to format $edevice"

  <% end %>
<% else -%>
  # We are setting up an ephemeral RAID, try to mount it
  try_mount_raid
  if [ $? -eq 1 ]; then
    # Didn't mount, so we have to do some work
    case $ephemeral_count in
      0)
      # Do nothing
        ;;
      1)
        req_fmt="<%=@data.ephemeral.raid.format%>"
        mnt_pnt="<%=get_mount('raid', :ephemeral)%>"
        device_is_mounted $drives &&
        [ "`check_device_format $drives`" == "$req_fmt" ] && return 0
        # If not mounted already
        sed -i "/`echo $mnt_pnt | cut -d'/' -f 2`/d" /etc/fstab

        fmt_as $req_fmt $drives &&
        mount -t $req_fmt -o noatime $drives $mnt_pnt
        Return1Fail
        echo "$drives $mnt_pnt $req_fmt noatime,nodiratime,defaults,comment=knifebseph 0 2" >> /etc/fstab
        ;;
      *)
        service mdadm stop
        # Multiple ephemeral, make RAID
        for d in $drives; do
          wipe_blocks $d
          # Delete fstab entry, if exists
          sed -i "/`echo $d | cut -d'/' -f 2`/d" /etc/fstab
        done

        umount -f <%=get_mount('raid', :ephemeral)%> &> /dev/null

        service mdadm start

        partprobe

        mdadm --manage `get_ephemeral_raid_dev` --stop > /dev/null 2>&1
        mdadm --create --name=<%=@data.ephemeral.raid.name%> --verbose /dev/md0 \
          --level=0 -c256 --raid-devices=$ephemeral_count $drives
        Return1Fail

        # setup mdadm.conf so on node restart it's fast
        echo DEVICE $drives | tee /etc/mdadm/mdadm.conf
        echo "`mdadm --detail --scan`" | tee -a /etc/mdadm/mdadm.conf

        fmt_as <%=@data.ephemeral.raid.format%> /dev/md0
        blockdev --setra 65536 /dev/md0
        [ ! -e $mnt_pnt ] && mkdir <%=get_mount('raid', :ephemeral)%>
        mount -t <%=@data.ephemeral.raid.format%> -o noatime /dev/md0 <%=get_mount('raid', :ephemeral)%>
        Return1Fail
        ;;
    esac
  fi
<% end %>
  return 0
}
